"""
Restaurants seed — Cartagena gastronomic catalog.
Source: user-provided spreadsheet "RESTAURANTES_EN_CARTAGENA.xlsx" (Feb 2026).
All restaurants are 4+ stars on TripAdvisor / Google.

Subcategory keys MUST match frontend RESTAURANT_SUBCATEGORIES in
app/(tabs)/partners.tsx:
  cafe | mediterranean | fastfood | italian | asian | colombian |
  seafood | international | gastronomic | vegetarian
"""

from typing import List, Dict, Any

# Default Unsplash banner per cuisine for partners without a custom image.
DEFAULT_IMG_BY_SUB = {
    "cafe":          "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    "mediterranean": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop",
    "fastfood":      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop",
    "italian":       "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=600&fit=crop",
    "asian":         "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&h=600&fit=crop",
    "colombian":     "https://images.unsplash.com/photo-1518176258769-f227c798150e?w=800&h=600&fit=crop",
    "seafood":       "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800&h=600&fit=crop",
    "international": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop",
    "gastronomic":   "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop",
    "vegetarian":    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
}

# Cartagena Old Town centroid lat/lng (used when no per-restaurant location).
CARTAGENA_CENTER = (10.4220, -75.5482)


def _r(idx: int, name: str, sub: str, *,
       description: str = "",
       address: str = "Cartagena de Indias, Colombia",
       instagram: str = "",
       website: str = "",
       cuisine: str = "",
       tier: str = "popular",
       price_range: str = "$$",
       rating: float = 4.5,
       reviews: int = 0,
       image_url: str = "",
       experience: str = "") -> Dict[str, Any]:
    """Helper to build a partner doc with sensible defaults."""
    return {
        "partner_id": f"ptr_R{idx:03d}",
        "name": name,
        "category": "restaurant",
        "subcategory": sub,
        "tier": tier,
        "description": description or f"Restaurante en Cartagena. Categoría: {cuisine or sub}.",
        "image_url": image_url or DEFAULT_IMG_BY_SUB.get(sub, DEFAULT_IMG_BY_SUB["gastronomic"]),
        "location": {"lat": CARTAGENA_CENTER[0], "lng": CARTAGENA_CENTER[1]},
        "address": address,
        "booking_link": website,
        "instagram": instagram,
        "price_range": price_range,
        "cuisine": cuisine or sub.capitalize(),
        "rating": rating,
        "reviews": reviews,
        "experience": experience or "Cocina · Cócteles · Ambiente local",
        "is_certified": True,
    }


# ─────────────────────────────────────────────────────────────────────
# Catálogo curado (Feb 2026)
# ─────────────────────────────────────────────────────────────────────
RESTAURANTS: List[Dict[str, Any]] = [
    # ── ASIÁTICO (asian) ─────────────────────────────────────────────
    _r(  1, "Niku",        "asian", tier="premium", price_range="$$$",
        description="Cocina nikkei y japonesa de autor. Producto fresco, sushi de alto nivel.",
        instagram="nikucartagena", website="https://nikucartagena.com",
        cuisine="Nikkei · Japonés", rating=4.6, reviews=620,
        address="Centro Histórico, Cartagena"),
    _r(  2, "Nami",        "asian", tier="popular", price_range="$$",
        description="Sushi y rolls de fusión asiática. Ambiente moderno y carta amplia.",
        instagram="namicartagena", cuisine="Sushi · Asiático", rating=4.4, reviews=410),
    _r(  3, "Pezetarian",  "asian", tier="popular", price_range="$$",
        description="Sushi y poke bowls con producto fresco. Espacio limpio, ideal para almorzar.",
        instagram="pezetarian", website="https://pezetarian.com",
        cuisine="Sushi · Poke", rating=4.5, reviews=520,
        address="Bocagrande, Cartagena"),
    _r(  4, "Hamachi",     "asian", tier="premium", price_range="$$$",
        description="Sushi premium y barra omakase. Una referencia de la cocina japonesa en Cartagena.",
        instagram="hamachicartagena", cuisine="Sushi · Omakase", rating=4.6, reviews=480),
    _r(  5, "Kona",        "asian", tier="popular", price_range="$$",
        description="Fusión asiática-caribeña, woks y sushi. Espacio relajado y moderno.",
        instagram="konacartagena", cuisine="Asiático · Fusión", rating=4.4, reviews=320),
    _r(  6, "Vive La Vida","asian", tier="popular", price_range="$$",
        description="Sushi bar y cocina asiática casual en pleno centro.",
        instagram="vivelavidacartagena", cuisine="Asiático", rating=4.3, reviews=270),
    _r(  7, "Koyo",        "asian", tier="popular", price_range="$$",
        description="Cocina japonesa contemporánea con ramen, gyozas y rolls de autor.",
        instagram="koyocartagena", cuisine="Japonés", rating=4.5, reviews=380),
    _r(  8, "Sr. Miyagi",  "asian", tier="popular", price_range="$$",
        description="Sushi bar con ambiente acogedor. Rolls creativos y carta de sake.",
        instagram="srmiyagicartagena", cuisine="Sushi · Japonés", rating=4.4, reviews=290),

    # ── COLOMBIANO (colombian) ───────────────────────────────────────
    _r( 11, "Candé",       "colombian", tier="premium", price_range="$$$",
        description="Folklore y gastronomía caribeña tradicional con shows en vivo. Una institución.",
        instagram="candecartagena", website="https://restaurantecande.com",
        cuisine="Caribeño tradicional", rating=4.5, reviews=2840,
        experience="Show de danza folclórica, cocina costeña, terraza colonial"),
    _r( 12, "La Mulata",   "colombian", tier="popular", price_range="$",
        description="Cocina caribeña casera. Menú del día económico y muy querido por locales.",
        instagram="lamulatacartagena", cuisine="Caribeño · Casero", rating=4.5, reviews=3210,
        address="Calle Quero, Centro Histórico"),
    _r( 13, "San Pasqual", "colombian", tier="premium", price_range="$$$",
        description="Cocina colombiana refinada con producto del Caribe. Patio colonial precioso.",
        instagram="sanpasqualcartagena", website="https://sanpasqual.co",
        cuisine="Colombiano contemporáneo", rating=4.6, reviews=910),
    _r( 14, "Santo Toribio","colombian", tier="popular", price_range="$$",
        description="Cocina tradicional cartagenera servida en un ambiente histórico del Centro.",
        instagram="santotoribiocartagena", cuisine="Tradicional", rating=4.4, reviews=720),
    _r( 15, "Kazabe",      "colombian", tier="premium", price_range="$$$",
        description="Cocina caribeña creativa. Honor a las raíces gastronómicas de la costa.",
        instagram="kazabecartagena", cuisine="Caribeño moderno", rating=4.6, reviews=540),
    _r( 16, "Macarena",    "colombian", tier="popular", price_range="$$",
        description="Cocina costeña con toques modernos en pleno corazón colonial.",
        instagram="macarenacartagena", cuisine="Costeño", rating=4.4, reviews=480),
    _r( 17, "San Nicolás", "colombian", tier="popular", price_range="$$",
        description="Restaurante de cocina colombiana en casa histórica del Centro.",
        instagram="sannicolascartagena", cuisine="Colombiano", rating=4.4, reviews=410),
    _r( 18, "Doña Lola",   "colombian", tier="popular", price_range="$",
        description="Cocina casera costeña. Sancochos, pescados fritos y arroz con coco.",
        instagram="donalolacartagena", cuisine="Casero · Costeño", rating=4.3, reviews=620),

    # ── DEL MAR (seafood) ────────────────────────────────────────────
    _r( 21, "Juan del Mar","seafood", tier="premium", price_range="$$$",
        description="Restaurante icónico de mariscos en Plaza San Diego. Pizzas, pastas y pescados.",
        instagram="juandelmar_cartagena", website="https://juandelmar.com",
        cuisine="Mariscos · Pizzas", rating=4.4, reviews=2640,
        address="Plaza de San Diego, Centro"),
    _r( 22, "Buena Vida Marisquería","seafood", tier="premium", price_range="$$$",
        description="Marisquería con producto fresco del Caribe. Ostras, ceviches y pescados al carbón.",
        instagram="buenavidamarisqueria", website="https://buenavidamarisqueria.com",
        cuisine="Mariscos", rating=4.5, reviews=860),
    _r( 23, "Rabo de Pez", "seafood", tier="premium", price_range="$$$",
        description="Cocina del mar con producto del día y carta de coctelería. Atmósfera elegante.",
        instagram="rabodepezcartagena", cuisine="Mariscos", rating=4.5, reviews=470),
    _r( 24, "Mar de las Antillas","seafood", tier="popular", price_range="$$",
        description="Cocina caribeña marinera con ceviches y pescados al estilo de las Antillas.",
        instagram="mardelasantillas", cuisine="Caribeño · Mariscos", rating=4.4, reviews=380),
    _r( 25, "Mar y Zielo", "seafood", tier="premium", price_range="$$$",
        description="Restaurante de mariscos con vista. Producto del día, carta amplia.",
        instagram="maryzielo", cuisine="Mariscos", rating=4.5, reviews=510),
    _r( 26, "Marea",       "seafood", tier="elite", price_range="$$$$",
        description="Marisquería gourmet del chef Jorge Rausch con vista al mar Caribe.",
        instagram="marea_rausch", website="https://marearausch.com",
        cuisine="Marisquería gourmet", rating=4.6, reviews=810,
        address="Bocagrande, Cartagena",
        experience="Vista al mar, mariscos, cava de vinos"),
    _r( 27, "Lobo de Mar", "seafood", tier="popular", price_range="$$",
        description="Cocina del mar con producto fresco y ambiente casual.",
        instagram="lobodemarcartagena", cuisine="Mariscos", rating=4.3, reviews=320),
    _r( 28, "Mardeleva",   "seafood", tier="premium", price_range="$$$",
        description="Cocina caribeña con producto del mar local. Diseño moderno en Getsemaní.",
        instagram="mardelevacartagena", website="https://mardeleva.com",
        cuisine="Caribeño · Mariscos", rating=4.5, reviews=680,
        address="Calle del Arsenal, Getsemaní"),
    _r( 29, "Fuerte San Sebastián","seafood", tier="premium", price_range="$$$",
        description="Restaurante en el histórico Fuerte de San Sebastián del Pastelillo. Vista a la marina.",
        instagram="fuertesansebastian", cuisine="Mariscos", rating=4.5, reviews=940,
        address="Manga, Cartagena"),
    _r( 30, "Manglar",     "seafood", tier="popular", price_range="$$",
        description="Cocina caribeña con producto del mar y ambiente acogedor.",
        instagram="manglarcartagena", cuisine="Mariscos · Caribeño", rating=4.4, reviews=410),
    _r( 31, "La Cevichería","seafood", tier="popular", price_range="$$",
        description="Marisquería de culto recomendada por Anthony Bourdain. Cebiches frescos.",
        instagram="lacevicheriacartagena", cuisine="Cebiche · Mariscos", rating=4.5, reviews=2640,
        address="Calle Stuart, San Diego"),
    _r( 32, "D'Pez",       "seafood", tier="popular", price_range="$$",
        description="Pescados y mariscos al estilo cartagenero. Buena relación calidad-precio.",
        instagram="dpezcartagena", cuisine="Mariscos", rating=4.3, reviews=280),
    _r( 33, "Clero Restaurant","seafood", tier="premium", price_range="$$$",
        description="Cocina del mar en una hermosa casa colonial. Experiencia gastronómica completa.",
        instagram="clerocartagena", cuisine="Mariscos · Gourmet", rating=4.6, reviews=510),

    # ── ITALIANO (italian) ───────────────────────────────────────────
    _r( 41, "Norma",       "italian", tier="premium", price_range="$$$",
        description="Cocina italiana auténtica con pastas frescas y pizzas al horno de leña.",
        instagram="normacartagena", website="https://normacartagena.com",
        cuisine="Italiano", rating=4.5, reviews=720),
    _r( 42, "Benitto",     "italian", tier="popular", price_range="$$",
        description="Trattoria italiana acogedora. Pastas caseras y carta de vinos.",
        instagram="benittocartagena", cuisine="Italiano · Trattoria", rating=4.4, reviews=380),
    _r( 43, "Fornaio",     "italian", tier="popular", price_range="$$",
        description="Pizzas al horno de piedra y pastas frescas en el corazón del Centro.",
        instagram="fornaiocartagena", cuisine="Pizzas · Italiano", rating=4.4, reviews=290),
    _r( 44, "Casa della Pasta Don Ignazio","italian", tier="popular", price_range="$$",
        description="Pastas hechas a mano, recetas familiares italianas auténticas.",
        instagram="donignaziocartagena", cuisine="Pastas · Italiano", rating=4.5, reviews=510),
    _r( 45, "Di Silvio Trattoria","italian", tier="popular", price_range="$$",
        description="Trattoria italiana con pizzas, pastas y ambiente familiar.",
        instagram="disilviocartagena", cuisine="Italiano", rating=4.4, reviews=470),
    _r( 46, "Da Pietro",   "italian", tier="popular", price_range="$$",
        description="Cocina italiana tradicional. Lasañas, risottos y postres caseros.",
        instagram="dapietrocartagena", cuisine="Italiano", rating=4.3, reviews=240),
    _r( 47, "Mariola",     "italian", tier="popular", price_range="$$",
        description="Pizzería y trattoria con producto local. Pizzas napolitanas excelentes.",
        instagram="mariolacartagena", cuisine="Pizza · Italiano", rating=4.5, reviews=420),

    # ── INTERNACIONAL (international) — incluye árabe, mediterraneo mixto, etc.
    _r( 51, "Juliette & Yoyo — Casa Bohème","international", tier="premium", price_range="$$$",
        description="Bistro francés-mediterráneo en la histórica Casa Bohème. Brunch y cena elegantes.",
        instagram="casabohemecartagena", website="https://casaboheme.co",
        cuisine="Bistro francés", rating=4.5, reviews=720),
    _r( 52, "Carta Ajena", "international", tier="premium", price_range="$$$",
        description="Cocina de autor en patio colonial. Carta cambiante con producto local.",
        instagram="cartaajena", cuisine="Cocina de autor", rating=4.6, reviews=380),
    _r( 53, "Casa Histórica 1927","international", tier="premium", price_range="$$$",
        description="Restaurante en una casa de 1927. Cocina internacional con toques caribeños.",
        instagram="casahistorica1927", cuisine="Internacional", rating=4.5, reviews=490),
    _r( 54, "Palosanto",   "international", tier="premium", price_range="$$$",
        description="Cocina latinoamericana con producto local. Espacio bonito y servicio impecable.",
        instagram="palosantocartagena", cuisine="Latinoamericano", rating=4.6, reviews=620),
    _r( 55, "El Gobernador","international", tier="elite", price_range="$$$$",
        description="Restaurante del Hotel Bastión Luxury. Cocina contemporánea de alta gama.",
        instagram="elgobernadorcartagena", website="https://bastionluxuryhotel.com",
        cuisine="Alta cocina", rating=4.7, reviews=540),
    _r( 56, "Ana Restaurante","international", tier="premium", price_range="$$$",
        description="Cocina mediterránea contemporánea en un espacio cálido y elegante.",
        instagram="anarestaurante", cuisine="Mediterráneo · Internacional", rating=4.5, reviews=380),
    _r( 57, "1811",        "international", tier="elite", price_range="$$$$",
        description="Restaurante de cocina internacional en el Hotel Charleston Santa Teresa.",
        instagram="hotelcharlestoncartagena", website="https://hotelcharlestoncartagena.com",
        cuisine="Internacional · Gourmet", rating=4.6, reviews=820),
    _r( 58, "Magnolia",    "international", tier="premium", price_range="$$$",
        description="Cocina internacional con buen producto local. Atmósfera elegante.",
        instagram="magnoliacartagena", cuisine="Internacional", rating=4.5, reviews=410),
    _r( 59, "Ely",         "international", tier="premium", price_range="$$$",
        description="Cocina contemporánea con influencias mediterráneas y caribeñas.",
        instagram="elycartagena", cuisine="Contemporáneo", rating=4.5, reviews=340),
    _r( 60, "El Arsenal",  "international", tier="popular", price_range="$$",
        description="Bar-restaurante de Getsemaní con cocina internacional y cocktails.",
        instagram="elarsenalcartagena", cuisine="Internacional", rating=4.4, reviews=280),
    _r( 61, "Kanuu",       "international", tier="popular", price_range="$$",
        description="Cocina creativa con producto local. Espacio cálido en el Centro.",
        instagram="kanuucartagena", cuisine="Cocina creativa", rating=4.4, reviews=210),
    _r( 62, "7 Cielos",    "international", tier="premium", price_range="$$$",
        description="Restaurante rooftop con vista panorámica al centro histórico.",
        instagram="7cieloscartagena", cuisine="Internacional · Rooftop", rating=4.5, reviews=560),
    _r( 63, "El Pasquín de Joaco","international", tier="popular", price_range="$$",
        description="Bar-restaurante con cocina internacional y ambiente bohemio.",
        instagram="elpasquindejoaco", cuisine="Internacional", rating=4.4, reviews=240),
    _r( 64, "Tito Bravo",  "international", tier="popular", price_range="$$",
        description="Cocina latina y parrilla en ambiente acogedor.",
        instagram="titobravocartagena", cuisine="Latino · Parrilla", rating=4.4, reviews=180),
    _r( 65, "Quebracho",   "international", tier="premium", price_range="$$$",
        description="Parrilla argentina con cortes premium y vinos sudamericanos.",
        instagram="quebrachocartagena", website="https://quebrachorestaurante.com",
        cuisine="Parrilla argentina", rating=4.6, reviews=920),
    _r( 66, "La Cabrera",  "international", tier="premium", price_range="$$$",
        description="Cadena argentina premium de parrilla. Cortes secos, vinos y postres clásicos.",
        instagram="lacabreracartagena", website="https://lacabrera.com.ar",
        cuisine="Parrilla argentina", rating=4.5, reviews=780),
    _r( 67, "La Chula",    "international", tier="popular", price_range="$$",
        description="Cocina mexicana auténtica con tacos, tequila y mezcales.",
        instagram="lachulacartagena", cuisine="Mexicano", rating=4.4, reviews=420),
    _r( 68, "Buffalo Grill","international", tier="popular", price_range="$$",
        description="Cadena de carnes y parrilla con cortes americanos. Ideal para familia.",
        instagram="buffalogrillco", website="https://buffalogrill.com.co",
        cuisine="Parrilla · Internacional", rating=4.2, reviews=380),

    # ── Árabe / Mediterráneo Mixto (clasificado como international según preferencia)
    _r( 71, "El Burlador", "mediterranean", tier="premium", price_range="$$$",
        description="Tapas y vinos españoles en una casa colonial restaurada. Romántico y con encanto.",
        instagram="elburladorsevilla", website="https://elburladordesevilla.com",
        cuisine="Español · Tapas", rating=4.4, reviews=1180),
    _r( 72, "M Cocina Árabe","international", tier="popular", price_range="$$",
        description="Cocina árabe-mediterránea: kebabs, hummus, tabule, falafel. Ambiente acogedor.",
        instagram="mcocinaarabe", cuisine="Árabe · Mediterráneo", rating=4.5, reviews=510),
    _r( 73, "Harissa",     "international", tier="popular", price_range="$$",
        description="Cocina marroquí y mediterránea. Tagines, cuscús y dulces árabes auténticos.",
        instagram="harissacartagena", cuisine="Marroquí · Mediterráneo", rating=4.5, reviews=290),
    _r( 74, "Restaurante Árabe Bocagrande","international", tier="popular", price_range="$$",
        description="Cocina árabe tradicional en Bocagrande. Kebabs, kibbeh y postres orientales.",
        instagram="arabebocagrande", cuisine="Árabe", rating=4.3, reviews=320),
    _r( 75, "Habbab",      "international", tier="popular", price_range="$$",
        description="Comida árabe libanesa servida con generosidad. Una institución local.",
        instagram="habbabcartagena", cuisine="Libanés · Árabe", rating=4.4, reviews=680),
    _r( 76, "Tahini Kebab","international", tier="popular", price_range="$",
        description="Kebabs, falafel y comida árabe rápida. Casual y económico.",
        instagram="tahinikebab", cuisine="Árabe · Kebabs", rating=4.3, reviews=410),

    # ── FAST FOOD (fastfood) ─────────────────────────────────────────
    _r( 81, "Home Burgers","fastfood", tier="popular", price_range="$$",
        description="Hamburguesas premium con producto local. Una de las mejores cadenas del país.",
        instagram="homeburgers", website="https://homeburgers.co",
        cuisine="Hamburguesas", rating=4.5, reviews=920),
    _r( 82, "Taco Beach",  "fastfood", tier="popular", price_range="$$",
        description="Tacos, burritos y comida mexicana casual en ambiente playero.",
        instagram="tacobeachcartagena", cuisine="Mexicano · Casual", rating=4.3, reviews=480),
    _r( 83, "Atrium",      "fastfood", tier="popular", price_range="$$",
        description="Food court con varias opciones rápidas y de calidad.",
        instagram="atriumcartagena", cuisine="Variado", rating=4.2, reviews=310),
    _r( 84, "Distrito",    "fastfood", tier="popular", price_range="$$",
        description="Espacio gastronómico con múltiples cocinas rápidas y bar.",
        instagram="distritocartagena", cuisine="Foodhall", rating=4.4, reviews=620),
    _r( 85, "Onecheez",    "fastfood", tier="popular", price_range="$$",
        description="Pizzas, quesos artesanos y comida casual.",
        instagram="onecheezpizza", cuisine="Pizza · Casual", rating=4.3, reviews=280),
    _r( 86, "Reina Arepa", "fastfood", tier="popular", price_range="$",
        description="Arepas colombianas en múltiples versiones. Rápido y delicioso.",
        instagram="reinaarepa", cuisine="Arepas · Colombiano", rating=4.4, reviews=720),
    _r( 87, "El Corral",   "fastfood", tier="popular", price_range="$$",
        description="Cadena colombiana de hamburguesas. Clásico nacional.",
        instagram="elcorralcolombia", website="https://elcorral.com",
        cuisine="Hamburguesas", rating=4.2, reviews=1240),
    _r( 88, "D'Gyros",     "fastfood", tier="popular", price_range="$",
        description="Gyros y shawarmas al estilo griego/turco. Rápido y económico.",
        instagram="dgyroscartagena", cuisine="Gyros · Shawarma", rating=4.3, reviews=380),
    _r( 89, "Porthos",     "fastfood", tier="popular", price_range="$$",
        description="Hamburguesas y comida casual en ambiente relajado.",
        instagram="porthoscartagena", cuisine="Hamburguesas · Casual", rating=4.2, reviews=240),
    _r( 90, "La Pepita",   "fastfood", tier="popular", price_range="$",
        description="Comida rápida saludable con opciones colombianas modernas.",
        instagram="lapepitacartagena", cuisine="Rápido · Saludable", rating=4.3, reviews=210),

    # ── GASTRONÓMICOS (gastronomic) — alta cocina / Latin Top 50 / autores
    _r(101, "Celele",      "gastronomic", tier="elite", price_range="$$$$",
        description="Cocina caribeña de autor del chef Jaime Rodríguez. Latin America's 50 Best Restaurants.",
        instagram="celelecartagena", website="https://restaurantecelele.com",
        cuisine="Caribeño de autor", rating=4.7, reviews=1240,
        experience="Menú degustación, recetas ancestrales, sommelier"),
    _r(102, "Carmen",      "gastronomic", tier="elite", price_range="$$$$",
        description="Cocina contemporánea con producto local. Una de las mejores experiencias de Cartagena.",
        instagram="carmencartagena", website="https://carmen.com.co",
        cuisine="Cocina de autor", rating=4.7, reviews=1850,
        experience="Menú degustación, cócteles signature, tasting room"),
    _r(103, "Donjuán",     "gastronomic", tier="premium", price_range="$$$$",
        description="Cocina caribeña moderna del chef Juan Felipe Camacho.",
        instagram="donjuancartagena", website="https://donjuancartagena.com",
        cuisine="Caribeño moderno", rating=4.6, reviews=1420),
    _r(104, "Alma",        "gastronomic", tier="elite", price_range="$$$$",
        description="Restaurante del Hotel Casa San Agustín. Cocina colombiana refinada en patio colonial.",
        instagram="almarestaurante", website="https://hotelcasasanagustin.com",
        cuisine="Colombiano refinado", rating=4.6, reviews=980),
    _r(105, "Restaurante 1621","gastronomic", tier="elite", price_range="$$$$",
        description="Restaurante del Sofitel Santa Clara. Fine dining en un antiguo convento colonial.",
        instagram="sofitelcartagena", website="https://sofitelcartagena.com",
        cuisine="Fine dining", rating=4.7, reviews=1320),
    _r(106, "Inkanto",     "gastronomic", tier="premium", price_range="$$$",
        description="Cocina peruana contemporánea con cebiches, tiraditos y cocina nikkei.",
        instagram="inkantocartagena", cuisine="Peruano", rating=4.6, reviews=620),
    _r(107, "Erre",        "gastronomic", tier="elite", price_range="$$$$",
        description="Cocina del chef Ramón Freixa (2 estrellas Michelin) en el Hotel Las Américas.",
        instagram="errecartagena", website="https://hotellasamericas.com.co",
        cuisine="Alta cocina española", rating=4.6, reviews=420),
    _r(108, "Lucena",      "gastronomic", tier="premium", price_range="$$$",
        description="Cocina de autor con producto local. Una propuesta gastronómica refinada.",
        instagram="lucenacartagena", cuisine="Cocina de autor", rating=4.5, reviews=290),

    # ── VEGETARIANO (vegetarian) ─────────────────────────────────────
    _r(121, "Vedana",      "vegetarian", tier="popular", price_range="$$",
        description="Cocina plant-based con menú creativo, bowls, smoothies y café.",
        instagram="vedanacartagena", cuisine="Vegetariano · Vegano", rating=4.6, reviews=380),
    _r(122, "Fit Choices", "vegetarian", tier="popular", price_range="$$",
        description="Comida saludable: bowls, ensaladas, smoothies y opciones veggie.",
        instagram="fitchoicescartagena", cuisine="Saludable · Veggie", rating=4.4, reviews=240),
    _r(123, "Vida",        "vegetarian", tier="popular", price_range="$$",
        description="Restaurante vegetariano con menú diario y opciones veganas.",
        instagram="vidacartagena", cuisine="Vegetariano", rating=4.4, reviews=190),
    _r(124, "Bajo la Palma","vegetarian", tier="popular", price_range="$$",
        description="Cocina saludable con producto local y opciones plant-based.",
        instagram="bajolapalmacartagena", cuisine="Saludable", rating=4.5, reviews=210),
    _r(125, "Gokela",      "vegetarian", tier="popular", price_range="$$",
        description="Bowls, ensaladas, smoothies y opciones healthy. Cadena confiable.",
        instagram="gokela", website="https://gokela.com",
        cuisine="Saludable · Bowls", rating=4.4, reviews=520),
    _r(126, "Santoco",     "vegetarian", tier="popular", price_range="$$",
        description="Café-restaurante con menú saludable y opciones vegetarianas.",
        instagram="santococartagena", cuisine="Saludable · Café", rating=4.4, reviews=180),
    _r(127, "Manna",       "vegetarian", tier="popular", price_range="$$",
        description="Cocina saludable y plant-based. Bowls, ensaladas y postres veganos.",
        instagram="mannacartagena", cuisine="Saludable · Vegano", rating=4.5, reviews=270),
    _r(128, "El Artesano", "vegetarian", tier="popular", price_range="$$",
        description="Café-restaurante con menú vegetariano artesanal y panadería propia.",
        instagram="elartesanocartagena", cuisine="Vegetariano · Café", rating=4.4, reviews=210),

    # ── CAFÉ / BRUNCH (cafe) ─────────────────────────────────────────
    _r(141, "Al Alma Café","cafe", tier="popular", price_range="$$",
        description="Café de especialidad con métodos manuales, pastelería y brunch.",
        instagram="alalmacafe", website="https://alalmacafe.com",
        cuisine="Café · Brunch", rating=4.6, reviews=820),
    _r(142, "La Brioche",  "cafe", tier="popular", price_range="$$",
        description="Pastelería y café francés. Croissants, brioches y desayunos clásicos.",
        instagram="labriochecartagena", cuisine="Café · Pastelería", rating=4.5, reviews=540),
    _r(143, "Prispi Coffee Shop","cafe", tier="popular", price_range="$",
        description="Café de especialidad y brunch en ambiente moderno. Antes era 'Se Volvió Prispi'.",
        instagram="prispicoffeeshop", cuisine="Café · Brunch", rating=4.5, reviews=320),
    _r(144, "San Pedro Café","cafe", tier="popular", price_range="$$",
        description="Café-restaurante con terraza en la Plaza San Pedro. Brunch y almuerzos.",
        instagram="sanpedrocafecartagena", cuisine="Café · Brunch", rating=4.4, reviews=410),
    _r(145, "Nia Bakery",  "cafe", tier="popular", price_range="$$",
        description="Panadería-pastelería francesa con croissants, tartas y café de especialidad.",
        instagram="niabakery", website="https://niabakery.co",
        cuisine="Panadería · Pastelería", rating=4.6, reviews=720),
    _r(146, "Café San Alberto","cafe", tier="premium", price_range="$$",
        description="Café de origen colombiano premium. Catas, métodos manuales y mucho conocimiento.",
        instagram="cafesanalberto", website="https://cafesanalberto.com",
        cuisine="Café de origen", rating=4.6, reviews=890),
    _r(147, "Érase Un Café","cafe", tier="popular", price_range="$$",
        description="Café-librería con encanto. Brunch, cafés especiales y ambiente bohemio.",
        instagram="eraseuncafe", cuisine="Café · Brunch", rating=4.5, reviews=480),
    _r(148, "Stefano Brunch","cafe", tier="popular", price_range="$$",
        description="Brunch italiano y café de especialidad. Decoración acogedora.",
        instagram="stefanobrunch", cuisine="Brunch · Italiano", rating=4.5, reviews=260),
    _r(149, "La Esquina del Pandebono","cafe", tier="popular", price_range="$",
        description="Pandebono fresco, café y desayunos típicos colombianos.",
        instagram="laesquinadelpandebono", cuisine="Panadería · Café", rating=4.4, reviews=340),
    _r(150, "Percimón",    "cafe", tier="popular", price_range="$$",
        description="Café de especialidad con repostería y opciones de brunch.",
        instagram="percimoncafe", cuisine="Café · Brunch", rating=4.5, reviews=190),
    _r(151, "Época",       "cafe", tier="popular", price_range="$$",
        description="Café-bistro de Getsemaní. Café especial, brunch y almuerzos saludables.",
        instagram="epocacartagena", cuisine="Café · Bistro", rating=4.5, reviews=380),
]
