// Curated occasion collections — mirror of backend occasions.COLLECTIONS (Drop 9: 21).
// Used by the home rail and as offline fallback on the collection screen.
export const COLLECTION_DEFS: Record<string, {
  icon: string; title_es: string; title_en: string; desc_es: string; desc_en: string;
  tags_any: string[]; categories?: string[];
}> = {
  'cena-romantica': { icon: 'heart', title_es: 'Cenas Románticas', title_en: 'Romantic Dinners', desc_es: 'Velas, patios coloniales y música para dos', desc_en: 'Candlelit colonial courtyards for two', tags_any: ['romantic'], categories: ['restaurant', 'bar'] },
  'rooftops-atardecer': { icon: 'sunny', title_es: 'Rooftops al Atardecer', title_en: 'Sunset Rooftops', desc_es: 'La hora dorada sobre la ciudad amurallada', desc_en: 'Golden hour above the walled city', tags_any: ['rooftop', 'sunset'], categories: ['bar', 'restaurant', 'hotel', 'nightlife'] },
  'primera-cita': { icon: 'cafe', title_es: 'Primera Cita', title_en: 'First Date', desc_es: 'Con encanto, para conversar sin exagerar', desc_en: 'Charming and easy to talk over', tags_any: ['first_date'], categories: ['bar', 'cafe', 'restaurant'] },
  'con-ninos': { icon: 'happy', title_es: 'Con Niños', title_en: 'Kid-Friendly', desc_es: 'Donde los peques también gozan', desc_en: 'Where the little ones have fun too', tags_any: ['kid_friendly', 'family'], categories: ['cafe', 'restaurant', 'attraction', 'beach_club'] },
  'dia-de-lluvia': { icon: 'rainy', title_es: 'Día de Lluvia', title_en: 'Rainy Day', desc_es: 'Bajo techo y con aire — que llueva', desc_en: 'Indoors and cool — let it pour', tags_any: ['indoor'], categories: ['attraction', 'cafe', 'activity'] },
  'musica-en-vivo': { icon: 'musical-notes', title_es: 'Música en Vivo', title_en: 'Live Music', desc_es: 'Salsa, son y champeta en directo', desc_en: 'Salsa, son and champeta, live', tags_any: ['live_music'], categories: ['bar', 'nightlife', 'restaurant', 'cafe'] },
  'favoritos-locales': { icon: 'location', title_es: 'Favoritos Locales', title_en: 'Local Favorites', desc_es: 'Donde comen los cartageneros, no los tours', desc_en: 'Where cartageneros actually eat', tags_any: ['local_favorite'], categories: ['restaurant', 'cafe'] },
  'cafe-desayuno': { icon: 'cafe', title_es: 'Café y Desayuno', title_en: 'Coffee & Breakfast', desc_es: 'Café de origen y el mejor arranque del día', desc_en: 'Origin coffee and the best start to the day', tags_any: ['coffee', 'breakfast'], categories: ['cafe', 'restaurant'] },
  'brunch': { icon: 'restaurant', title_es: 'Brunch', title_en: 'Brunch', desc_es: 'Media mañana de fin de semana, con ambiente', desc_en: 'Weekend late-morning, with ambiance', tags_any: ['brunch'], categories: ['cafe', 'restaurant', 'bar', 'hotel'] },
  'ceviche-mariscos': { icon: 'fish', title_es: 'Ceviche y Mariscos', title_en: 'Ceviche & Seafood', desc_es: 'Lo más fresco del Caribe', desc_en: 'The freshest of the Caribbean', tags_any: ['seafood', 'ceviche'], categories: ['restaurant'] },
  'street-food': { icon: 'fast-food', title_es: 'Street Food', title_en: 'Street Food', desc_es: 'Arepa de huevo, pinchos y dulces al momento', desc_en: 'Arepa de huevo, pinchos and sweets, fresh', tags_any: ['street_food'], categories: ['restaurant', 'attraction'] },
  'cocteles': { icon: 'wine', title_es: 'Coctelería de Autor', title_en: 'Cocktail Bars', desc_es: 'Los mejores tragos de la ciudad', desc_en: 'The city\'s best cocktails', tags_any: ['cocktails'], categories: ['bar', 'nightlife', 'restaurant'] },
  'rumba': { icon: 'musical-notes', title_es: 'Rumba y Baile', title_en: 'Dancing & Nightclubs', desc_es: 'Donde se baila hasta tarde (jue–sáb)', desc_en: 'Where the city dances late (Thu–Sat)', tags_any: ['nightlife', 'dancing'], categories: ['nightlife', 'bar'] },
  'grupo-fiesta': { icon: 'people', title_es: 'Planes de Grupo', title_en: 'Group & Party', desc_es: 'Yates, islas de fiesta y noche en grupo', desc_en: 'Yachts, party islands and group nights', tags_any: ['group', 'party'], categories: ['beach_club', 'nightlife', 'yacht', 'service'] },
  'beach-clubs': { icon: 'umbrella', title_es: 'Beach Clubs', title_en: 'Beach Clubs', desc_es: 'Islas y playas — de fiesta a familia', desc_en: 'Islands and beaches — party to family', tags_any: ['beach'], categories: ['beach_club', 'hotel'] },
  'saludable': { icon: 'leaf', title_es: 'Saludable y Veggie', title_en: 'Healthy & Vegan', desc_es: 'Bowls, veggie y opciones conscientes', desc_en: 'Bowls, veggie and mindful options', tags_any: ['healthy'], categories: ['restaurant'] },
  'cafes-trabajo': { icon: 'laptop', title_es: 'Cafés para Trabajar', title_en: 'Work-Friendly Cafés', desc_es: 'Wifi, enchufes y ambiente para portátil', desc_en: 'Wifi, outlets and a laptop-friendly vibe', tags_any: ['work_friendly'], categories: ['cafe', 'restaurant'] },
  'postres': { icon: 'ice-cream', title_es: 'Postres y Dulces', title_en: 'Dessert & Sweets', desc_es: 'Gelato, paletas y patisserie para refrescar', desc_en: 'Gelato, popsicles and patisserie to cool off', tags_any: ['dessert'], categories: ['cafe', 'restaurant', 'attraction'] },
  'spa-bienestar': { icon: 'flower', title_es: 'Spa y Bienestar', title_en: 'Wellness & Spa', desc_es: 'Rituales y masajes en los mejores spas', desc_en: 'Rituals and massages at the top spas', tags_any: ['wellness', 'spa'], categories: ['wellness'] },
  'ocasion-especial': { icon: 'sparkles', title_es: 'Ocasión Especial', title_en: 'Special Occasion', desc_es: 'Para celebrar en grande — mesas icónicas', desc_en: 'To celebrate big — iconic tables', tags_any: ['special_occasion'], categories: ['restaurant'] },
  'lujo-total': { icon: 'diamond', title_es: 'Lujo Total', title_en: 'Pure Luxury', desc_es: 'Lo más elite de Cartagena — hoteles legendarios y alta cocina', desc_en: 'Cartagena\'s most elite — legendary hotels and fine dining', tags_any: ['luxury'], categories: ['restaurant', 'hotel', 'beach_club', 'yacht', 'wellness'] },
};
